---
title: "What is Gospel Analysis?"
description: |
  Our **mission** is to invite others to learn of Christ through His
  Scriptures, both past and present.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

> "We believe all that God has revealed, all that He does now reveal, and we believe that He will yet reveal many great and important things pertaining to the Kingdom of God." [Articles of Faith #9](https://www.churchofjesuschrist.org/study/scriptures/pgp/a-of-f/1.9?lang=eng#8)

At Gospel Analysis, we believe that "All scripture is given by inspiration of God"
([2 Tim 3:16](https://www.churchofjesuschrist.org/study/scriptures/nt/2-tim/3.16?lang=eng#15)) and that words spoken by the Holy Ghost are "the words of Christ" ([2 Nephi 32:3](https://www.churchofjesuschrist.org/study/scriptures/bofm/2-ne/32.3?lang=eng#2)). We study and analyze all text that's scripture. Like Nephi, our souls "[delight] in proving unto [our] people the truth of the coming of Christ" [2 Nephi 11:4](https://www.churchofjesuschrist.org/study/scriptures/bofm/2-ne/11.4?lang=eng#3).

We focus here on Christian texts often studied by members of The Church of Jesus Christ of Latter-day Saints, which include scriptures in The Book of Mormon: Another Testament of Jesus Christ, The New Testament, The Old Testament, The Doctrine and Covenants, and The Pearl of Great Price as well as General Conference Talks. Other scriptures, such as the
[Apocrypha](https://www.churchofjesuschrist.org/study/scriptures/dc-testament/dc/91?lang=eng), could be of interest, but are out of scope for this project.

## Disclaimer

This site is not affiliate with The Church of Jesus Christ of Latter-day Saints.
The opinions and stances of authors are their own. 

## Contribute with Us

If you'd like to participate by asking a question or becoming an author, send an email to gospelanalysisnow@gmail.com. We'd love your contributions.

  
