---
title: "Second Coming of Jesus Christ"
description: |
  The usage of the phrase "second coming" in the scriptures
author:
  - name: Bryan Whiting
    url: https://www.bryanwhiting.com
date: 09-01-2021
output:
  distill::distill_article:
    self_contained: false
categories:
   - general conference
   - scriptures
   - second coming
   - jesus christ
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE
  )
```


```{r}
library(generalconference)
library(scriptuRs)
library(dplyr)
library(tidytext)
library(ggplot2)
source("/home/rstudio/gospel_analysis_blog/_posts/ggtheme.R")
source("/home/rstudio/gospel_analysis_blog/_posts/utils.R")

colors = palette_pander(10)
# extrafont::loadfonts() ## to load the font
options(max.print=1000)
data("genconf")
dfg <- genconf %>%
  unnest(sessions) %>%
  unnest(talks) %>%
  unnest(paragraphs) %>%
  mutate(paragraph2 = tolower(paragraph))
  
dfs <- lds_scriptures() %>%
  mutate(text2 = tolower(text))
```

# How often is `second coming` mentioned?

The exact phrase "second coming" is only mentioned once in all of the scriptures:

```{r, results="asis"}
dfs %>% 
  filter(str_detect(text2, "second coming")) %>%
  quote_verse("second coming")
```

Yet this verse is mentioned often in General Conference:

```{r}
cnt <- dfg %>%
  filter(str_detect(paragraph2, "second coming")) %>%
  count(year)
# View(cnt)
cnt %>%
  ggplot(aes(x = year, y = n)) +
  geom_bar(stat='identity', fill=colors[1]) +
  labs(
    title = 'Number of References to "Second Coming"',
    subtitle = "By year",
    y = ''
  ) + 
  theme_ga
```

It was mentioned a lot in the mid 70's, but seems to be picking back up again.
