---
title: "Ask and Ye Shall Receive"
description: |
  How have the Prophets asked and received answers?  
author:
  - name: Bryan Whiting
    url: https://www.bryanwhiting.com
date: 09-15-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
draft: true
categories:
   - general conference
   - scriptures
   - ask
---


```{r setup, include=FALSE}
slug <- "ask" # basename(getwd())
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
```

```{r load}
View(mtcars)
plot(x, y, ...)
here::i_am(fs::path("_posts", slug, slug, ext = "Rmd"))
pkgs <- c(
  "generalconference", "scriptuRs", "instaquote",
  "dplyr", "gt", "tidytext", "DT", "reactable", "htmltools", "here"
)
for (p in pkgs) library(p, character.only = T)
source(here("R/ggtheme.R"), local = knitr::knit_global())
source(here("R/utils.R"), local = knitr::knit_global())

colors <- palette_pander(10)
# extrafont::loadfonts() ## to load the font
options(max.print = 1000)
data("genconf")
dfg <- genconf %>%
  unnest(sessions) %>%
  unnest(talks) %>%
  unnest(paragraphs) %>%
  mutate(
    paragraph2 = tolower(paragraph),
    date_str = date %>% format("%b %Y"),
    deep_link = glue("{url}.{p_id}?lang=eng#{p_id}"),
    p_href = glue('{author1} <a href="{deep_link}">{title1}</a>, {date_str}'),
    pquote = glue("{paragraph}<br>{p_href}"),
    # https://stackoverflow.com/a/26406796
    n_words = str_count(paragraph2, "\\S+")
  )

dfs <- lds_scriptures() %>%
  mutate(text2 = tolower(text)) %>%
  mutate(text_w_ref = glue("{verse_short_title}\n{text2}"))
```

# Ask

```{r}
dfs %>% 
    select(volume_long_title, text_w_ref) %>%
    filter(str_detect(text_w_ref, "give|receiv")) %>%
    ask(text_w_ref, 'ask', n = 500) 

p <- instaquote(
  title = "Whatsoever thou wilt ask of god, god will give it thee.",
  subtitle = "Mark 6:23",
  title_size = 20
)
make_post(
  img = p,
  title = "64 times in the scriptures appears the words 'ask' with 'give'",
  body = "",
  slug = slug,
  name = 'iq_ask64give',
  is_quote = T
)
```
